package com.learnII;

/**
 * Created by Prem Chand on 9/22/2016.
 * class defined as ABSTRACT cannot be initiated
 * If method is abstract there should be any implementation of such methods in subclass
 * abstract method is meant to be overridden in subclass which will be extending abstract classes
 * abstract class need not have abstract methods but
 * if any class has a abstract method than that class should be abstract class.
 * abstract class are also called as non concrete class as they don't have implementation of methods
 * a concrete class extending abstract class should override/implementation all the abstract method of no concrete
 * and if we don't want to override/implement abstract method in subclass extending abstract class than subclass should he abstract as well
 * abstract method cannot be private because abstract method should be overridein this sub class so .. it has be public so that we can use out of class
 * method marked as static cannot be abstract because static method can be initiated by ClassName but abstract method cannot be initiated it is only
 * initi by object in overriden class
 * Final cannot be abstract because Final cannot be overridden
 * C:\MyStuff\javaCourse\abstractClass.png
 * Abstract class can have constructor if not default constructor will be generated by compiler
 * Abstract class constructor will be invoked when subclass object is created .
 */
public abstract class AbstractClassDemo {
    public static void main(String[] args) {
//        AbstractClassDemo abstractClassDemo = new AbstractClassDemo(); >> this is not allowed for abstract class
    }

    public void methodDefined() {
        // this is allowed but  class should be abstract if they have any abstract method but not vice versa
    }

//    private abstract void privateMethod();  >> this illegal as all the abstract methods need to be overridden in its subclass.

    //    public abstract void abstractMethod(){} >> tis is not allowed

//    public abstract static void staticMethodNotAllowed(); >> not allowed as  static method can be invoked by class name

    public abstract void abstractMethod();//>> this is allowed correct, abstract method is meant to be overridden in subclass

}
