package com.PatternSearching;

/**
 * @author prem chand shah on 01-03-2018
 * @project myJava
 */
public class PatternMatching {

    public static void search(String txt, String pat) {
        long startTime = System.nanoTime();
        int M = pat.length();
        int N = txt.length();

        /* A loop to slide pat one by one */
        for (int i = 0; i <= N - M; i++) {

            int j;

            /* For current index i, check for pattern
              match */
            for (j = 0; j < M; j++)
                if (txt.charAt(i + j) != pat.charAt(j))
                    break;

            if (j == M) // if pat[0...M-1] = txt[i, i+1, ...i+M-1]
                System.out.println("Pattern found at index " + i);

            long endTime = System.nanoTime();
            long totalTime = endTime - startTime;
            System.out.println("Total time: " + totalTime);
        }
    }


    public static void matchAtIndex(String pat, String text) {
        int Psize = pat.length();
        int Tsize = text.length();

        // i <= Tsize - Psize because no need to compare last 3 char as it will not have matching string .
        for (int i = 0; i <= Tsize - Psize; i++) {
            int j;
            for (j = 0; j < Psize; j++)
                if (text.charAt(i + j) != pat.charAt(j))
                    break;
            if (j == Psize)
                System.out.println("Pattern match at index" + i);
        }
    }

    public static void main(String[] args) {
        String txt = "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB" +
                "ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABxABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABx" +
                "ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABABDABACDABABCABABxABABDABACDABABCABABxABABDABACDABABCABABxABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABDABACDABABCABABxABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABABABABDABACDABABCABAB\" +\n" +
                "                \"ABABDABACDABABCABABxx" +
                "";
        String pat = "ABABDABACDABABCABABxx";
        search(txt, pat);
        System.out.println("---------");
        //matchAtIndex(pat, txt);
    }
}
